controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # position_controller:
    #   type: position_controllers/JointGroupPositionController

# position_controller:
#   ros__parameters:
#     joints:
#       - FR_HAA
#       - FR_HFA
#       - FR_KFE
#       # - FR_ANKLE
#       - FL_HAA
#       - FL_HFA
#       - FL_KFE
#       # - FL_ANKLE
#     interface_name: position
